version: '3.7'

services:
  redis:
    image: redis:5.0.0-alpine
    ports:
      - 6379:6379
    environment:
      REDIS_HOST: redis
      REDIS_PORT: 6379

  zipkin:
    image: openzipkin/zipkin
    ports:
      - 9411:9411

  eureka:
    build:
      context: ./eureka/
      dockerfile: Dockerfile
    image: discovery-service
    ports:
      - 8761:8761
    environment:
      EUREKA_HOST: eureka

  catalog:
    build:
      context: ./catalog/
      dockerfile: Dockerfile
    image: catalog-service
    ports:
      - 8081:8081
    environment:
      EUREKA_HOST: eureka
      EUREKA_PORT: 8761
      ZIPKIN_HOST: zipkin
      ZIPKIN_PORT: 9411
    depends_on:
      - redis
      - eureka

  inventory:
    build:
      context: ./inventory/
      dockerfile: Dockerfile
    image: inventory-service
    ports:
      - 8082:8082
    environment:
      EUREKA_HOST: eureka
      EUREKA_PORT: 8761
      ZIPKIN_HOST: zipkin
      ZIPKIN_PORT: 9411
    depends_on:
      - eureka

  product:
    build:
      context: ./product/
      dockerfile: Dockerfile
    image: product-service
    ports:
      - 8083:8083
    environment:
      EUREKA_HOST: eureka
      EUREKA_PORT: 8761
      ZIPKIN_HOST: zipkin
      ZIPKIN_PORT: 9411
    depends_on:
      - eureka

networks:
  default:
    driver: bridge